# Generated by Django 5.1.1 on 2024-09-24 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Maker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "American Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "Pound Sterling"),
                    ("CNY", "Chinese Yuan"),
                    ("INR", "Indian Rupee"),
                    ("JPY", "Japanese Yen"),
                    ("KRW", "South Korean Won"),
                    ("RUB", "Russian Ruble"),
                    ("IRR", "Iranian Rial"),
                    ("SEK", "Swedish Krona"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=512),
        ),
        migrations.AddField(
            model_name="product",
            name="maker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="store.maker",
            ),
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("icon_url", models.URLField(blank=True)),
                ("description", models.TextField()),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children_categories",
                        to="store.productcategory",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="store.productcategory",
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
