# Generated by Django 5.1.1 on 2024-09-24 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_maker_product_currency_alter_product_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcategory",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
